In [ ]:
pip install numpy

belajar menggunakan numpy

In [ ]:
import numpy as np

In [ ]:
list1 = np.array([1,2,3,4,5,6])
print(list1)
print(type(list1))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


jika kita mengimpor numpy pada codenya jgn lupa menggunakan np (np merupakan inisial dari numpy yang kita buat dan ditambah dengan array di sampin np. berikut ini contoh yang lain:

In [ ]:
#cth yg lain
list2 = np.array((1,2,3,4,5,6,7,8,9))
print(list2)

[1 2 3 4 5 6 7 8 9]


In [ ]:
#cara untuk memeriksa area list1 untuk melihat brpa bnyk anggota yg di milki
list2.shape

(9,)

kemudian numpy juga bisa membuat matriks dimana dalam matriks terdapat baris dan kolom

In [ ]:
list3 = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(list3)
list3.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

dalam numpy kita dapat membuat matriks nol dengan menggunakan atribut"zeros" berikut ini cara nya:


In [ ]:
nol = np.zeros((3,4))
print(nol)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


kita juga dapat membuat matriks 3d yakni sebagai berikut.

In [ ]:
matrix_3d = np.zeros((2, 3, 4))
print(matrix_3d)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


selain zero, kita dapat menggunakan ones biar sragam dalam matriks

In [ ]:
satu =np.ones((4,5))
print (satu)
dua = np.ones((3,))
print(dua)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[1. 1. 1.]


array of a particular value = dimana kita dapat membuat nilai tertentu. kita dapat menggunakan np.full untuk menggunakan nilai tertentu.

In [ ]:
# array of a particular
z = np.full((3,4),7)
print(z)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


dalam numpy dapat di membuat matrik identitas yang mana isinya adalah angka 0 dan angka 1 dalam bentuk diagonal dan dalam penulisan kode cukup sekali saja tidak seperti yang di atas kita menentukan kolom dan baris seperti (4,5). kita hanya memasukkan angka satu saja karena matriks identitas harus berbentuk persegi. Dalam penggunaanya kita menggunakan numpy jenis eye. berikut cth nya:

In [ ]:
b = np.eye((4))
print(b)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


membuat matriks dengan nilai angka random. disini kita dapat membuat matriks dengan angkanya yang random dengan menggunakan numpy

In [ ]:
np.set_printoptions(precision=6, suppress=True)
#kode diatas merupakan precision untuk menentukan jumlah angka desimal yang ingin
#Anda tampilkan dan suppress untuk menonaktifkan notasi ilmiah

In [ ]:
#menggunakan numpy dengan angka random
c = np.random.random ((3,4))
print(c)

[[0.892851 0.458493 0.121223 0.692628]
 [0.265271 0.870301 0.659479 0.680205]
 [0.457035 0.807118 0.422362 0.858637]]


menggunakan np.random.random akan menghasilkan output hanya berada di kisaran 0 sampai 1. tidak ada yang kurang dari 0 maupun di atas 1.

kita dapat menggunakan numpy dengan angka random bilang bulat serta membuat batasan pada bilangan bulat random. kode yang digunakan adalah np.random.randint

In [ ]:
g = np.random.randint(12,200,(4,5))
print(g)

[[189 188 196 137  32]
 [170 108 191 158 166]
 [ 62 156 165  24 118]
 [151  93 131  67 136]]


angka 12 adalah angka awal angka 200 adalah angka akhir. angka 4 dan 5 adlh jumlah baris dan kolom. dengan menggunakan randint tidak dibatasi antara 0 sampai 1.

numpy jg dapat mendukung untuk bilangan berkelipatan seperti kelipatan 5 kelipatan 6 dll. kode yang digunakan adalah np.linspace. yang membedakan linspace dengan np.random adalah bhwa linspace ditentukan kelipatannya dengan num di blkang nilai batas. setelah menentukan batas sedangan np.random ini merupakan atribut yang mengambil nilai random.

dalam penggunaan num emng otomatis oleh dengan numpy namun untuk mengetahui operasi penggunaan num adalah rumusnya sebagai berikut:
b-a/n-1
b = adalah nilai akhir
a = adalah nilai awal
n = adalah jumlah angka yang dihasilkan

contoh:
np.linspace(12,72,6)
maka perhitungannya:
(72 - 12) / (6 - 1) = 60 / 5 = 12
maka kelipatannya adalah 12

In [ ]:
s = np.linspace(12,72,6)
print(s)
#12 adalah angka awal, 72 angka akhir, dan 6 adalah bilangan kelipatan


[12. 24. 36. 48. 60. 72.]


In [ ]:
arr = np.linspace(1,10,50)
print(arr)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


kemudian dapat juga membuat kelipatan jg namun nilai awal dan akhir tidak diikuti. disini menggunakan kelipatan secara langsung. arange langsung eksekusi bahwa kelipatan 5 dan tanpa perhitungan sprti linspace.

In [ ]:
h = np.arange(10,30,5)
print(h)

[10 15 20 25]


ingat satu hal. dalam list dan tuple kita dapat mengubah tipe data nya menjadi array numpy

In [ ]:
list3 = [10,20,30,40]
halo = np.array(list3)
print(halo)
print(type(halo))

[10 20 30 40]
<class 'numpy.ndarray'>


==analysing a numpy array===

dalam analisis dapat menghitung jumlah anggota di dalam matriks.

In [ ]:
b = np.eye(5)
print(b)
c = np.size (b)
print (c)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
25


In [ ]:
zet = np.random.randint(1,65,(4,4))
print(zet)

[[47 55 16 35]
 [48 42 58 12]
 [39 40  5 49]
 [ 8 19 55 19]]


In [ ]:
print(zet.shape)

(4, 4)


pada analiys dapat menggunakan pengecekkan dimensi suatu matriks. dengan menggunakan (nama).ndim

In [ ]:
biru = zet.ndim
print(biru)

#atau langsung di lakukan pencetakan jg bisa

print(zet.ndim)

2
2


kita dapat  menentukan jenis data yang disimpan dalam array NumPy yakni dengan menggunakan numpy dengan code dtype

In [ ]:
print (zet.dtype)

int64


pada numpy dapat kita jumlahkan pada variabel kita dibandingkan dengan kita melakukan penjumlah tanpa numpy yang mana akan menjadi 2 gabungan.

In [ ]:
#tanpa numpy
data1 = [1,2,3,4,5]
data2 = [6,7,8,9,10]
print(data1 + data2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


dari kode di atas tanpa menggunakan atribut dari numpy hanya melakukan penggabungan antara data1 dan data 2

In [ ]:
number = np.array([1,2,3,4,5])
count = np.array([6,7,8,9,10])
print(number + count)
print (number - count)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]


dari cara di atas dapat dilakukan operasi perhitungan matematika

numpy dapat menambahkan var nya dengan kode yg diberikan secara langsung. yakni menggunakan add (tambah), subtract(kurang), divide (pembagian), dan multiply (perkalian)

In [ ]:
result_add = np.add([1, 2, 3], [4, 5, 6])
print(result_add)

result_multiply = np.multiply([1, 2, 3], [4, 5, 6])
print(result_multiply)

result_subtract = np.subtract([1, 2, 3], [4, 5, 6])
print(result_subtract)

result_divide = np.divide([1, 2, 3], [4, 5, 6])
print(result_divide)

[5 7 9]
[ 4 10 18]
[-3 -3 -3]
[0.25 0.4  0.5 ]


dalam perkalian matriks di numpy ada 2 cara kita lakuan. yang pertama adalah menggunakan dot (np.dot).

In [ ]:
#cara pertama menggunakan np.dot(a,b)
a = np.array(([1,2], [3,4]))
b = np.array(([5,6], [7,8]))
c = np.dot(a,b)
print(c)

matriks a: [[1 2]
 [3 4]]
[[19 22]
 [43 50]]


In [ ]:
#cara kedua menggunakan a.dot(b)
a = np.array(([1,2], [3,4]))
b = np.array(([5,6], [7,8]))
c = a.dot(b)
print(c)

[[19 22]
 [43 50]]


penggunaan numpy dapat melakukan manipulasi array. salah satu yang digunakan yaitu transpose

In [ ]:
# penggunaan transpose dari kolom ke baris baris ke kolom, begitu jg dengan angka - angkanya akan berubah tempat yakni dari kolom ke baris
# baris ke kolom
arr = np.random.randint(1, 11, (2, 3))
print (arr)
print(arr.shape)

print(8*('*'))

trans = np.transpose(arr)
print (trans)
print (trans.shape)

[[ 3  3  5]
 [ 1  9 10]]
(2, 3)
********
[[ 3  1]
 [ 3  9]
 [ 5 10]]
(3, 2)


numpy dapat melakukan perubahan pd shape


In [ ]:
#mengubah shape menggunakan reshape
a = np.array(([1,2], [3,4], [5,6]))
print(a.reshape(2,3))
# yang awalnya baris 3 dan kolom 2, sekarang berubah menjadi 2 baris
# dan 3 kolom

[[1 2 3]
 [4 5 6]]


hanya seputaran kolom dan baris yang telah ditentukan tidak bisa merubah angka lebih besar lagi pada shape nya

In [ ]:
#melakukan latihan
a = np.arange(10)**2 #dengan menggunakan pangkat ini menandakan perhitungan dari 0 sampe 9 di pangkatkan 2
print(f"tolong cetak {a[:5]}")
print(f"tolong cetak {a[1:7]}")
print(f"tolong cetak {a[0:]}")

tolong cetak [ 0  1  4  9 16]
tolong cetak [ 1  4  9 16 25 36]
tolong cetak [ 0  1  4  9 16 25 36 49 64 81]


In [ ]:
a = np.arange(10)
for i in a:
  print(f"value: {i}")

value: 0
value: 1
value: 2
value: 3
value: 4
value: 5
value: 6
value: 7
value: 8
value: 9


kita dapat menggunakan transpose untuk mengubah kolom dan baris. baris menjadi kolom dan kolom menjadi baris.

In [ ]:
a = np.transpose(([1,2], [3,4], [5,6]))
print(a)

#atau bisa nulis kek gini
a = np.array (([1,2], [3,4], [5,6]))
print(a.transpose())

#dan kita dapat mempersingkatnya transpose menjadi T
a = np.array(([1,2], [3,4], [5,6]))
print(a.T)

[[1 3 5]
 [2 4 6]]
[[1 3 5]
 [2 4 6]]
[[1 3 5]
 [2 4 6]]


flatten array merupakan salah satu cara membuat variabel matriks menjadi baris semua. cthnya sebagai berikut:

In [ ]:
a = np.array (([1,2], [3,4], [5,6]))
print(a.ravel())

[1 2 3 4 5 6]



Fungsi resize dalam NumPy digunakan untuk mengubah ukuran array. Ini dapat digunakan untuk mengubah dimensi array atau jumlah elemen array

In [ ]:
# Membuat array 1D
a = np.array([1, 2, 3, 4, 5])
a.resize(3, 2)
print(a)

[[1 2]
 [3 4]
 [5 0]]


In [ ]:
list_1 = [1,2,3,4,5]
list_2 = [6,7,8,9,10]
list_3 = [11,12,13,14,15]
list_4 = np.array([list_1, list_2, list_3])
print(list_4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


pada kode di atas terlebih dahulu membuat list satu persatu untuk membuat 2 dimensi. kemudian dengan menggunakan array kita dapat menggabungkan list-list tsb menjadi satu array atau satu list bergabung menjadi satu. untuk membedakan list 1d, 2d, 3d adalah dengan cara melihat kurung kotaknya berapa. kalo satu itu 1d, 2 adalah 2d, dan 3 adalah 3d.

In [ ]:
abc = np.array (([1,2], [3,4], [5,6]))
dgf = abc.reshape(1,6)
print(dgf)

[[1 2 3 4 5 6]]


cara mencetak nilai di dalam array dalam array. disini kita menggunakan slicing untuk memanggil nilai nilai yang ada di dalam list.

In [ ]:
arr = ([[ 1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])
run =np.array(arr)
print(run)
print("*"*8)
print(run[0:1,2:4])
print("*"*8)
print(run[2:,4:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
********
[[3 4]]
********
[[15]]


kita dapat mengganti elemen dalam list dengan angka yang bil nya sama. jika nilai nya 1 sampe 9, mulai 3 keatas di ubah menjadi nilai seratus. itu bisa.

In [4]:
arr = [1,2,3,4,5,6,7,8,9]
print(arr)
arrb[3:]=100
print(arrb)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


NameError: name 'arrb' is not defined