In [1]:
pip install numpy

belajar menggunakan numpy

In [4]:
import numpy as np

list1 = np.array([1,2,3,4,5,6])
print(list1)
print(type(list1))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


jika kita mengimpor numpy pada codenya jgn lupa menggunakan np (np merupakan inisial dari numpy yang kita buat dan ditambah dengan array di sampin np. berikut ini contoh yang lain:

In [5]:
#cth yg lain
list2 = np.array((1,2,3,4,5,6,7,8,9))
print(list2)

[1 2 3 4 5 6 7 8 9]


In [7]:
#cara untuk memeriksa area list1 untuk melihat brpa bnyk anggota yg di milki
list2.shape

(9,)

kemudian numpy juga bisa membuat matriks dimana dalam matriks terdapat baris dan kolom

In [10]:
list3 = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(list3)
list3.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

dalam numpy kita dapat membuat matriks nol dengan menggunakan atribut"zeros" berikut ini cara nya:


In [15]:
nol = np.zeros((3,4))
print(nol)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


selain zero, kita dapat menggunakan ones biar sragam dalam matriks

In [18]:
satu =np.ones((4,5))
print (satu)
dua = np.ones((3,))
print(dua)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[1. 1. 1.]
